import{test} from "@playwright/test"
test("mouse action",async({page})=>{
    // await page.goto("https://demoapps.qspiders.com/ui/button?sublist=0")
    // await page.locator('#btn').click()
    // await page.waitForTimeout(2000)
    // await page.goto("https://demoapps.qspiders.com/ui/button/buttonRight?sublist=1")
    // await page.locator('#btn_a').click({button:'right'})
    // await page.waitForTimeout(2000)
    // await page.goto('https://demoapps.qspiders.com/ui/button/buttonDouble?sublist=2')
    // // await page.locator('#btn_a').dblclick()
    // await page.locator('#btn_a').click({clickCount:2})
        // await page.goto('https://demoapps.qspiders.com/ui/clickHold?sublist=0')
        // await page.locator('#circle').hover()
        // await page.mouse.down()
        // await page.waitForTimeout(2000)
        // await page.mouse.up()
        // await page.waitForTimeout(2000)
        // await page.goto("https://demoapps.qspiders.com/ui/button/buttonDisabled?sublist=4")
        // // await page.locator('#submitButton').click({force:true})
        // await page.locator('#submitButton').dispatchEvent('click')
        // await page.waitForTimeout(5000)
// await page.goto('https://demoapps.qspiders.com/ui/mouseHover?sublist=0')
//     await page.locator('//img[@class="w-5 h-5 mt-5 ml-3 cursor-pointer "]').hover()
//     await page.waitForTimeout(3000)
//     await page.mouse.move(100,200)
//     await page.waitForTimeout(5000)

// await page.goto("https://demoapps.qspiders.com/ui/scroll/newTabVertical")
//  await page.waitForTimeout(3000)
// await page.locator('[type="checkbox"]').scrollIntoViewIfNeeded()
//  await page.waitForTimeout(3000)
// await page.goto("https://demoapps.qspiders.com/ui/scroll/newTabHorizontal")
// await page.waitForTimeout(5000)
// await page.mouse.wheel(1000,1000)
// await page.waitForTimeout(3000)
// await page.mouse.wheel(-1000,0)
// await page.waitForTimeout(5000)
// await page.goto("https://demoapps.qspiders.com/ui/scroll/newTabVertical")
// await page.waitForTimeout(5000)
// await page.mouse.wheel(1000,1000)
// await page.waitForTimeout(3000)
// await page.mouse.wheel(0,1000)
// await page.waitForTimeout(5000)

// await page.goto('https://demoapps.qspiders.com/ui/dragDrop?sublist=0')
//     await page.locator('//div[text()="Drag Me"]').hover()
//     await page.waitForTimeout(2000)
//     await page.mouse.down()
//     await page.mouse.move(200,500)
//      await page.waitForTimeout(2000)
//      await page.mouse.up()

// await page.goto('https://demoapps.qspiders.com/ui/dragDrop/dragToCorrect?sublist=2')
// await page.locator('//div[text()="Mobile Charger"]').hover()
//  await page.waitForTimeout(2000)
// await page.mouse.down()
// await page.locator('//div[text()="Mobile Accessories"]/parent::div').hover()
// await page.mouse.up()
// //   await page.waitForTimeout(2000)


// await page.goto('https://demoapps.qspiders.com/ui/dragDrop/dragToCorrect?sublist=2')
// await page.locator('//div[text()="Mobile Charger"]').hover()
//  await page.waitForTimeout(2000)
// await page.mouse.down()
// let box = await page.locator('//div[text()="Mobile Accessories"]/parent::div').boundingBox()
// await page.mouse.move(box.x,box.y)
// await page.mouse.up()
//   await page.waitForTimeout(2000)


//   await page.goto('https://demoapps.qspiders.com/ui/dragDrop/dragToCorrect?sublist=2')
// let source=page.locator('//div[text()="Mobile Charger"]')
// let target=page.locator('//div[text()="Mobile Accessories"]/parent::div')
// await page.waitForTimeout(5000)
// await source.dragTo(target)
//  await page.waitForTimeout(5000)
// })