import{test} from "@playwright/test"
test("test",async({page})=>{
    // await page.goto('https://www.amazon.in/')
    // await page.getByPlaceholder("Search Amazon.in")
    // await page.keyboard.insertText("iphone17 pro")
//     await page.goto(" https://www.instagram.com/")
//     await page.locator('#_r_6_')
//     await page.keyboard.insertText("98765643210")
// await page.keyboard.press("Tab")    
// await page.keyboard.insertText("alexender")
    
// await page.goto("https://demoapps.qspiders.com/ui/button?sublist=0")
// await page.locator('#btn').click({button:'left'})
// await page.waitForTimeout(2000)
// await page.locator('#btn_two').click({button:'left'})
// await page.waitForTimeout(2000)
// await page.locator('#btn').click({button:'left'})
// await page.waitForTimeout(2000)
// await page.locator('#btn_two').click({button:'left'})
// await page.waitForTimeout(2000)
// await page.locator('#btn').click({button:'left'})
// await page.waitForTimeout(2000)
// await page.locator('#btn_two').click({button:'left'})
// await page.waitForTimeout(2000)
// await page.locator('#btn').click({button:'left'})
// await page.waitForTimeout(2000)
// await page.locator('#btn_two').click({button:'left'})
await page.goto("https://demoapps.qspiders.com/ui/checkbox?sublist=0")
await page.waitForTimeout(5000)
await page.locator('#domain_a').isChecked()
await page.waitForTimeout(5000)
await page.mouse.click({})
})